### ISSUE TITLE
1주차 진행

### ISSUE THREAD

**Issue by hyunjune-lee** [CodeSoom/project-spring-4-hyunjune-lee#3]
1. 이 앱을 언제 사용하나요?
자신이 배웠던 지식들을 정리하고 체계적으로 관리할 수 있게 해줍니다. 
2. 제약 조건은 무엇인가요?
    1. 기록 - 기억하고 싶은 지식을 기록할 수 있어야 합니다.(플래시카드 형식으로 기록 - 질문과 답)
    2. 체계화 - 지식들을 학습 날짜별 목록이나 트리 형식 등으로 한눈에 체계적으로 볼 수 있어야 합니다. 또한 학습 진행 정도도 확인할 수 있어야 합니다.
    3. 학습 - 자신이 기억하고 싶은 지식을 플래시카드 학습법으로 학습하고 학습 진행정도를 기억합니다.
    + 사용자가 설정한 학습 방향성에 따라 오늘 학습할 지식들을 추천해줍니다.
    - + 변환 - md 형식의 텍스트를 넣으면 바로 플래시 카드 및 트리로 변환시켜줍니다.
3. 구체적인 사례는 무엇인가요?
오늘 배웠던 지식들을 계속 기억하고 싶으면 이 앱에 기록합니다. 체계적으로 정리된 지식 트리를 보면서 학습이 잘 된 부분과 학습이 부족한 부분을 한 눈에 파악합니다. 기억하고 싶은 지식들은 플래시카드 학습법을 통해 학습을 진행합니다. 이때 학습이 잘 진행될수록 해당 지식은 초록색으로 칠해지고, 학습이 안 된 부분은 빨간색으로 칠해집니다.
4. 이번 주가 지나면 사용자는 무엇을 할 수 있나요?
기억할 지식들을 기록할 수 있습니다.(플래시 카드 형식으로)
지식을 자신이 기록한 날짜별로, 학습해야되는 날짜별로 api로 응답받습니다.
5. 이번 주 에 구현할 기능을 우선순위대로 작성해 주세요.
    - [ ]  지식 카드 도메인 설계하기
    - [ ]  지식을 플래시카드 형식으로 받아서 기록하기
    - [ ]  기록한 날짜별로, 학습해야되는 날짜별로 api 응답해주기

**Comment by johngrib** [comment]
플래시 카드 참 좋죠. 구상한 아이디어를 그려둔 그림이나 비슷한 서비스가 있다면 메모에 같이 추가해둬도 괜찮습니다.

**Comment by hyunjune-lee** [comment]
네! 다른 사람들도 아이디어를 이해하기 쉽도록 구상한 그림이나 참고했던 비슷한 서비스를 계속 추가해나갈게요!
